apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "binpacking-exporter.fullname" . }}
  labels:
    {{- include "binpacking-exporter.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods"]
    verbs: ["get", "list", "watch"]
