{{- if include "kube-binpacking-exporter.leaderElectionEnabled" . }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kube-binpacking-exporter.fullname" . }}-leader-election
  labels:
    {{- include "kube-binpacking-exporter.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kube-binpacking-exporter.fullname" . }}-leader-election
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-binpacking-exporter.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
