{{- if include "binpacking-exporter.leaderElectionEnabled" . }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "binpacking-exporter.fullname" . }}-leader-election
  labels:
    {{- include "binpacking-exporter.labels" . | nindent 4 }}
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update"]
{{- end }}
